### PR TITLE
fix: Change Jenkins X to JayeX in `jio-navbar`

### LINKED ISSUE #193: Change Jenkins X to JayeX in `jio-navbar`
Name of Jenkins X has been changed to JayeX two weeks ago which was officially announced by CDF foundation. 
reference: 
https://cd.foundation/blog/2026/04/16/announcing-jayex/?utm_content=375726637&utm_medium=social&utm_source=linkedin&hss_channel=lcp-19100461

### PR DESCRIPTION
**Pull request by Vatsal-Verma**
Name of Jenkins X has been changed to JayeX two weeks ago which was officially announced by CDF foundation. 
reference: 
https://cd.foundation/blog/2026/04/16/announcing-jayex/?utm_content=375726637&utm_medium=social&utm_source=linkedin&hss_channel=lcp-19100461

### Screenshot
image

closes #193

### CODE REVIEW

File: src/jio-navbar.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export class Navbar extends LitElement {
   override render() {
     const cdfMenuItems = [
       {label: msg("What is CDF?"), link: "https://cd.foundation/"},
-      {label: msg("Jenkins X"), link: "https://jenkins-x.io/"},
+      {label: msg("JayeX"), link: "https://jenkins-x.io/"},
```
Comment (krisstern) [inline src/jio-navbar.ts]:
```suggestion
      {label: msg("JayeX"), link: "https://jayex.io/"},
```

Comment (krisstern) [reply src/jio-navbar.ts]: I checked their URL changed as well

**Review by krisstern — CHANGES_REQUESTED** [review]

File: src/jio-navbar.ts (hunk 1 above)
Comment (Vatsal-Verma) [reply src/jio-navbar.ts]: They've added redirection from the old url to the new url.

Comment (krisstern) [reply src/jio-navbar.ts]: That's obvious, but we still need to update the URL

Comment (Vatsal-Verma) [reply src/jio-navbar.ts]: About the issue on the jenkins-infra/jenkins.io
Do we need to update the name and the url everywhere possible or only at some specific places ?

Comment (MarkEWaite) [reply src/jio-navbar.ts]: > Do we need to update the name and the url everywhere possible or only at some specific places ?

In my opinion, I think we should update it everywhere, except in blog posts.  We generally treat blog posts as historical items and do not modify them.  I don't think it makes sense to change items in the events archive, either.

I think that logos, page headers, menus, author descriptions, GSoC project ideas, projects redirects, and security reporting references should be updated.

Comment (Vatsal-Verma) [reply src/jio-navbar.ts]: @MarkEWaite Thank you for pointing the places. I did a github search on the jenkins-infra/jenkins repo and found the places where Jenkins X is used :)
https://github.com/search?q=repo%3Ajenkins-infra%2Fjenkins.io+%22Jenkins+X%22&type=code&p=1

there are 85 files including blogs posts and event archive. However, excluding those two, there are not many.

**Review by MarkEWaite — APPROVED** [review]

**Review by krisstern — APPROVED** [review]

File: src/jio-navbar.ts (hunk 1 above)
Comment (lemeurherve) [reply src/jio-navbar.ts]: Noting https://github.com/jenkins-infra/jenkins.io/issues/9095#issuecomment-4371317065
